### ISSUE TITLE
Dependencies released on asOf date not found

### ISSUE THREAD

**Issue by nickiemc** [corgibytes/freshli#162]
Currently, `IVersionInfo.DatePublished` includes the time that a dependency was published (e.g. `06/01/2017 11:32:57`). However, the `asOf` dates that are used during calculations assume a time of midnight (e.g. `06/01/2017 00:00:00`).

So, when calculating the values as of `6/1/2017` for a manifest that contains a dependency that was released at  `06/01/2017 11:32:57`, the dependency cannot be found.

The `asOf` dates should be updated to assume a time of `23:59:59`.

**Comment by nickiemc** [comment]
Relevant examples from https://github.com/explosion/spaCy:

  [`thinc>=6.7.0,<6.8.0`](https://github.com/explosion/spaCy/blob/ae8010b5262755c82ba82364932d6a8817e974c2/requirements.txt#L6) 
  [`murmurhash>=0.28,<0.29`](https://github.com/explosion/spaCy/blob/ae8010b5262755c82ba82364932d6a8817e974c2/requirements.txt#L7)

**Comment by dan-hein** [comment]
I have a question regarding the desired outcome of this change. Is the primary goal to assume that when the [default runner](https://github.com/corgibytes/freshli/blob/27a8b2397473fcc6399ce7d128a8de054919d8bd/Freshli/Runner.cs#L71) is called, then the end of the current day will be assumed for the asOf date? Or would we rather overwrite the time component passed into the [DateTime specific runner](https://github.com/corgibytes/freshli/blob/27a8b2397473fcc6399ce7d128a8de054919d8bd/Freshli/Runner.cs#L14) to be the last tick of the date component?

If the latter is the case, I'd like to suggest that we change the parameter passed into the specific runner to only accept the date as the time will not be used. Otherwise, this could potentially cause confusion for someone trying to specify an asOf DateTime time.

**Comment by nickiemc** [comment]
@dan-hein I think your first assumption is correct. We want to assume that the end of the current day is the `asOf` date so that any dependencies that were released earlier in the day of the `asOf` date are included in list of latest dependencies.

Does that help clarify?

**Comment by dan-hein** [comment]
I'm not sure I can reproduce this issue. I could definitely be interpreting the data wrong, but when I run Date 6/1/2017 00:00:00, I see 
`{"Name":"thinc","Version":">=6.7.0,<6.8.0","PublishedAt":"0001-01-01T00:00:00","LatestVersion":null,"LatestPublishedAt":"0001-01-01T00:00:00","Value":0.0,"UpgradeAvailable":false,"Skipped":true},`

And when I run the day prior the latest version I see is
`{"Name":"thinc","Version":"6.5.2","PublishedAt":"2017-03-20T12:39:50Z","LatestVersion":"6.5.2","LatestPublishedAt":"2017-03-20T12:39:50Z","Value":0.0,"UpgradeAvailable":false,"Skipped":false}`

Is this correct behavior? I also seem to get the same results at any time on 6/1/2017. I could definitely be wrong on this, but I think this might not be an issue anymore.
